/* See COPYING.txt for license details. */

/*
 * res_string.h
 */

#ifndef RES_STRING_H_
#define RES_STRING_H_

typedef enum{
	IDS_EMULATE,
	IDS_WRITE,
	IDS_EDIT,
	IDS_RENAME,
	IDS_DELETE,
	IDS_INFO,
	IDS_SAVE,
	IDS_READING,
	IDS_WRITING,
	IDS_EMULATING,
	IDS_RETRY,
	IDS_MORE,
	IDS_UNSAVED,
	IDS_CANCEL,
	IDS_NAME_,
	IDS_ENTER_HEX_DATA,
	IDS_ENTER_FILENAME,
	IDS_HOLD_CARD_,
	IDS_UNSUPPORTED_FILE_,
	IDS_DELETE_SUCCESS,
	IDS_DUPLICATE_FILE,
	IDS_BACK,
	IDS_REBOOT,
	IDS_REBOOT1,
	IDS_POWER_OFF,
	IDS_POWER_OFF1,
	IDS_SUCCESS,
	IDS_ERROR,

	IDS_CONSUMPTION,
	IDS_PRE_CHARGE,
	IDS_CHARGING,
	IDS_COMPLETE,
	IDS_INPUT_FAULT,
	IDS_THERMAL_SHUTDOWN,
	IDS_SAFETY_TIME_EXP,
	IDS_L,
	IDS_T,
	IDS_V,
	IDS_H,
	IDS_USER_DEFINED,//" ",
	IDS_USER_END,
}StringIdx_et;

const char * res_string(int str_id);

#endif /* RES_STRING_H_ */
